### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by cube-dan** [zafar-saleem/react-login#2]
Greets Zafar! Thanks for publishing this project on medium/github. You've helped bring clarity to an otherwise muddy field of [redux/saga enabled react router login tutorials](https://www.google.com/search?ei=qR-xXJO6J5b1-gT_tb_YDg&q=react-router+login+flow+with+redux+saga+&oq=react-router+login+flow+with+redux+saga+&gs_l=psy-ab.3...241623.248823..249224...0.0..0.122.1042.7j4......0....1j2..gws-wiz.......0i71j35i304i39j35i39j0i22i30.Gp5pIADOA14)

I'd like to fork and go to create a version of this project that bounces requests off [strapi](https://strapi.io/). Before I get too far into the weeds I'd like to make sure that you're cool with me going in a different direction using your code as a jumping off point.

Would you clarify the licence type for this project? Here's the github doc on [licencing](https://help.github.com/en/articles/licensing-a-repository)

Thanks for your time.

-Dan

**Comment by zafar-saleem** [comment]
Hi @cube-dan Just added LICENCE to this project. Feel free to use it. I am closing this issue now.

**Comment by cube-dan** [comment]
Thanks again Zafar for releasing this code!
